server:
  port: 8081

# mysql database configurations
# database source url
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scm
    username: root
    password: mysql

  #jpa configurations
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true


